AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.3

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

# Test describe blocks can be any size
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

# Use lenient line length
Metrics/LineLength:
  Max: 100

# Some of GnomeKeyring's functions have long parameter lists
Metrics/ParameterLists:
  Max: 7

# GirFFI uses a ffi-something naming scheme.
Naming/FileName:
  Enabled: false
