language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - 2.0.0
  - rbx-18mode
  - rbx-19mode
# libgirepository1.0-dev: provides /usr/lib/libgirepository-1.0.so
# gir1.2-gnomekeyring-1.0: provides /usr/lib/girepository-1.0/GnomeKeyring-1.0.typelib
before_install:
  - sudo apt-get update
  - sudo apt-get install libgirepository1.0-dev gir1.2-gnomekeyring-1.0
