language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - 2.0.0
  - rbx-18mode
  - rbx-19mode
before_install:
  - sudo apt-get update
  - sudo apt-get install libgirepository1.0-dev gobject-introspection libgnome-keyring-dev
matrix:
  allow_failures:
    - rvm: rbx-19mode
