language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - jruby-19mode
  - rbx-2
before_install:
  - sudo apt-get update
  # libgirepository1.0-dev: provides /usr/lib/libgirepository-1.0.so
  # gir1.2-gnomekeyring-1.0: provides /usr/lib/girepository-1.0/GnomeKeyring-1.0.typelib
  - sudo apt-get install libgirepository1.0-dev gir1.2-gnomekeyring-1.0
