sudo: required
dist: trusty
language: ruby

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgirepository1.0-dev gir1.2-gnomekeyring-1.0

rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-9.2
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head

branches:
  only:
    - master
