language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - ruby-head-clang
  - jruby-19mode
  - jruby-20mode
  - jruby-head
  - jruby-9.0.0.0
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: ruby-head-clang
before_install:
  - sudo apt-get update
  # libgirepository1.0-dev: provides /usr/lib/libgirepository-1.0.so
  # gir1.2-gnomekeyring-1.0: provides /usr/lib/girepository-1.0/GnomeKeyring-1.0.typelib
  - sudo apt-get install libgirepository1.0-dev gir1.2-gnomekeyring-1.0
