# frozen_string_literal: true

Gem::Specification.new do |spec|
  spec.name = "gir_ffi-gnome_keyring"
  spec.version = "0.0.11"
  spec.authors = ["Matijs van Zuijlen"]
  spec.email = ["matijs@matijs.net"]

  spec.summary = "GirFFI-based binding to GnomeKeyring"
  spec.description = "Bindings for GnomeKeyring generated by GirFFI, with overrides."
  spec.homepage = "http://www.github.com/mvz/gir_ffi-gnome_keyring"
  spec.license = "LGPL-2.1+"
  spec.required_ruby_version = ">= 2.6.0"

  spec.metadata["rubygems_mfa_required"] = "true"

  spec.files = File.read("Manifest.txt").split
  spec.rdoc_options = ["--main", "README.md"]
  spec.extra_rdoc_files = ["Changelog.md"]
  spec.require_paths = ["lib"]

  spec.add_runtime_dependency "gir_ffi", "~> 0.15.1"

  spec.add_development_dependency "minitest", "~> 5.0"
  spec.add_development_dependency "rake", "~> 13.0"
  spec.add_development_dependency "rake-manifest", "~> 0.2.0"
  spec.add_development_dependency "rubocop", "~> 1.24.0"
  spec.add_development_dependency "rubocop-minitest", "~> 0.17.0"
  spec.add_development_dependency "rubocop-performance", "~> 1.12.0"
end
